version: "3.4"

services:
  my-nginx:
    image: fholzer/nginx-brotli:latest
    container_name: my-nginx
    networks:
      - my-net
    volumes:
      - ./nginx/staging/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: always
  next-app:
    container_name: next-app
    image: next-app:latest
    build:
      context: ./next-app
      dockerfile: Dockerfile
      args:
      - APP_ENV=${APP_ENV}
      - CDN_URL=${CDN_URL}
      - API_BASE_URL=${API_BASE_URL}
      - CRITICAL_CSS_BASE_URL=http://penthouse-server:${PENTHOUSE_SERVER_PORT}/
      - PORT=${PORT}
    networks:
      - my-net
    volumes:
      - ./container-data/css:/usr/src/app/.data
    ports:
      - "3000:${NEXT_APP_PORT}"
    environment:
      - APP_ENV=${APP_ENV}
      - CDN_URL=${CDN_URL}
      - API_BASE_URL=${API_BASE_URL}
      - CRITICAL_CSS_BASE_URL=http://penthouse-server:${PENTHOUSE_SERVER_PORT}/
      - PORT=${NEXT_APP_PORT}
    restart: always
  penthouse-server:
    container_name: penthouse-server
    image: penthouse-server:latest
    build:
      context: ./penthouse-server
      dockerfile: Dockerfile
    networks:
      - my-net
    volumes:
      - ./container-data/css:/usr/src/app/css
      - ./container-data/critical-css:/usr/src/app/critical-css
    environment:
      - NEXT_APP_BASE_URL=http://next-app:${NEXT_APP_PORT}/
      - CSS_FILES_PATH=${CSS_FILES_PATH}
      - CRITCAL_CSS_FILES_PATH=${CRITCAL_CSS_FILES_PATH}
      - PORT=${PENTHOUSE_SERVER_PORT}
    restart: always
networks:
  my-net:
    driver: bridge
